### ISSUE TITLE
weird markdown rendering..uh

### ISSUE THREAD

**Issue by fenix011** [jhvanderschee/hugobricks#10]
Weird markdown rendering , e.g:

```
hugobricks/content/docs/settings/header.md
```

We might be missing some very basics here! :-|

It has maybe todo with... 

```
markup:
  goldmark:
    renderer:
      unsafe: true # Allow HTML in md files
    parser:
      attribute:
        block: true
        title: true
```

at config.yaml ?!
