### ISSUE TITLE
Best practices and/or enhanced support for i18n site

### ISSUE THREAD

**Issue by expersso** [jhvanderschee/hugobricks#55]
Loving this theme!

I'm trying to add i18n support, but I'm wondering about the best practice for url management. For example, let's say I implement a language switcher in the navbar like this:

```html
<div>
        <ul class="language-list">
            {{ range $.Site.Home.AllTranslations }}
            <li><a href="{{ .Permalink }}">{{ .Language.LanguageName }}</a></li>
            {{ end }}
        </ul>
</div>
```

This works, but it sends the user to the landing page, whereas
 I would prefer for it to link to e.g. /nl/about if you click on it while on the about page.

More importantly, I wonder about how to deal with the navbar links defined in `data/en/header.yaml`. Do I need to change the urls on all these manually for alternative languages, e.g.

```yaml
menuitems:
  - title: About Us in Dutch
    link: nl/about/
  - title: Contact us in Dutch
    link: nl/contact/
```

Or is there already support for automating this?

Lastly, could one add sitemap functionality that treats the main language as the canonical reference and lists alternative languages?
