### ISSUE TITLE
contactform placeholders broken

### ISSUE THREAD

**Issue by tamis-laan** [jhvanderschee/hugobricks#69]
``` yaml
action: /form.php
placeholders: true
fields: 
- name: title
  input_type: html
  placeholder: <h3>Tell us a bit about yourself</h3>
  required: true
- name: name
  input_type: text
  placeholder: Name
  required: true
```

Changing the placeholder for example `placeholder: Name` to `placeholder: John Doe` changes the title of the input. This is incorrect the `name: Name` should set the the title of the input and the placeholder should set the placeholder text when not filled in (in grey).
